name: Test

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["dev", "main"]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  # Test building the package
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip build

      - name: Build package
        shell: bash
        run: |
          python -m build --sdist --wheel

      - name: Install tarball
        shell: bash
        run: |
          python -m pip install dist/*.gz

      - name: Test installation
        shell: bash
        run: |
          specio
